//
//  JRMPokemon.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class JRMPokemonBuilder;
@class JRMSprites;
@class JRMStat;
@class JRMType;

NS_ASSUME_NONNULL_BEGIN

@interface JRMPokemon : NSObject<NSCopying, NSSecureCoding>
@property (nullable, nonatomic, strong, readonly) JRMSprites * sprites;
@property (nonatomic, assign, readonly) NSInteger height;
@property (nullable, nonatomic, copy, readonly) NSString * name;
@property (nonatomic, assign, readonly) BOOL isDefault;
@property (nonatomic, assign, readonly) NSInteger identifier;
@property (nonatomic, assign, readonly) NSInteger baseExperience;
@property (nonatomic, assign, readonly) NSInteger weight;
@property (nullable, nonatomic, strong, readonly) NSArray<JRMStat *> * stats;
@property (nonatomic, assign, readonly) NSInteger order;
@property (nullable, nonatomic, strong, readonly) NSArray<JRMType *> * types;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(JRMPokemonBuilder *)builder;
- (instancetype)initWithBuilder:(JRMPokemonBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(JRMPokemonBuilder *builder))block;
- (BOOL)isEqualToPokemon:(JRMPokemon *)anObject;
- (instancetype)mergeWithModel:(JRMPokemon *)modelObject;
- (instancetype)mergeWithModel:(JRMPokemon *)modelObject initType:(PlankModelInitType)initType;
@end

@interface JRMPokemonBuilder : NSObject
@property (nullable, nonatomic, strong, readwrite) JRMSprites * sprites;
@property (nonatomic, assign, readwrite) NSInteger height;
@property (nullable, nonatomic, copy, readwrite) NSString * name;
@property (nonatomic, assign, readwrite) BOOL isDefault;
@property (nonatomic, assign, readwrite) NSInteger identifier;
@property (nonatomic, assign, readwrite) NSInteger baseExperience;
@property (nonatomic, assign, readwrite) NSInteger weight;
@property (nullable, nonatomic, strong, readwrite) NSArray<JRMStat *> * stats;
@property (nonatomic, assign, readwrite) NSInteger order;
@property (nullable, nonatomic, strong, readwrite) NSArray<JRMType *> * types;
- (instancetype)initWithModel:(JRMPokemon *)modelObject;
- (JRMPokemon *)build;
- (void)mergeWithModel:(JRMPokemon *)modelObject;
@end

NS_ASSUME_NONNULL_END
