//
//  JRMSprites.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class JRMSpritesBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface JRMSprites : NSObject<NSCopying, NSSecureCoding>
@property (nullable, nonatomic, copy, readonly) NSString * frontShinyFemale;
@property (nullable, nonatomic, copy, readonly) NSString * frontShiny;
@property (nullable, nonatomic, copy, readonly) NSString * backFemale;
@property (nullable, nonatomic, copy, readonly) NSString * frontDefault;
@property (nullable, nonatomic, copy, readonly) NSString * backShiny;
@property (nullable, nonatomic, copy, readonly) NSString * backShinyFemale;
@property (nullable, nonatomic, copy, readonly) NSString * frontFemale;
@property (nullable, nonatomic, copy, readonly) NSString * backDefault;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(JRMSpritesBuilder *)builder;
- (instancetype)initWithBuilder:(JRMSpritesBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(JRMSpritesBuilder *builder))block;
- (BOOL)isEqualToSprites:(JRMSprites *)anObject;
- (instancetype)mergeWithModel:(JRMSprites *)modelObject;
- (instancetype)mergeWithModel:(JRMSprites *)modelObject initType:(PlankModelInitType)initType;
@end

@interface JRMSpritesBuilder : NSObject
@property (nullable, nonatomic, copy, readwrite) NSString * frontShinyFemale;
@property (nullable, nonatomic, copy, readwrite) NSString * frontShiny;
@property (nullable, nonatomic, copy, readwrite) NSString * backFemale;
@property (nullable, nonatomic, copy, readwrite) NSString * frontDefault;
@property (nullable, nonatomic, copy, readwrite) NSString * backShiny;
@property (nullable, nonatomic, copy, readwrite) NSString * backShinyFemale;
@property (nullable, nonatomic, copy, readwrite) NSString * frontFemale;
@property (nullable, nonatomic, copy, readwrite) NSString * backDefault;
- (instancetype)initWithModel:(JRMSprites *)modelObject;
- (JRMSprites *)build;
- (void)mergeWithModel:(JRMSprites *)modelObject;
@end

NS_ASSUME_NONNULL_END
