//
//  JRMSprites.m
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import "JRMSprites.h"

struct JRMSpritesDirtyProperties {
    unsigned int JRMSpritesDirtyPropertyBackDefault:1;
    unsigned int JRMSpritesDirtyPropertyBackFemale:1;
    unsigned int JRMSpritesDirtyPropertyBackShiny:1;
    unsigned int JRMSpritesDirtyPropertyBackShinyFemale:1;
    unsigned int JRMSpritesDirtyPropertyFrontDefault:1;
    unsigned int JRMSpritesDirtyPropertyFrontFemale:1;
    unsigned int JRMSpritesDirtyPropertyFrontShiny:1;
    unsigned int JRMSpritesDirtyPropertyFrontShinyFemale:1;
};

@interface JRMSprites ()
@property (nonatomic, assign, readwrite) struct JRMSpritesDirtyProperties spritesDirtyProperties;
@end

@interface JRMSpritesBuilder ()
@property (nonatomic, assign, readwrite) struct JRMSpritesDirtyProperties spritesDirtyProperties;
@end

@implementation JRMSprites
+ (NSString *)className
{
    return @"JRMSprites";
}
+ (NSString *)polymorphicTypeIdentifier
{
    return @"sprites";
}
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary
{
    return [[self alloc] initWithModelDictionary:dictionary];
}
- (instancetype)init
{
    return [self initWithModelDictionary:@{}];
}
- (instancetype)initWithModelDictionary:(NSDictionary *)modelDictionary
{
    NSParameterAssert(modelDictionary);
    if (!(self = [super init])) {
        return self;
    }
    [modelDictionary enumerateKeysAndObjectsUsingBlock:^(NSString *  _Nonnull key, id  _Nonnull obj, __unused BOOL * _Nonnull stop){
        if ([key isEqualToString:@"front_shiny_female"]) {
            id value = valueOrNil(modelDictionary, @"front_shiny_female");
            if (value != nil) {
                self->_frontShinyFemale = value;
            }
            self->_spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShinyFemale = 1;
        }
        if ([key isEqualToString:@"front_shiny"]) {
            id value = valueOrNil(modelDictionary, @"front_shiny");
            if (value != nil) {
                self->_frontShiny = value;
            }
            self->_spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShiny = 1;
        }
        if ([key isEqualToString:@"back_female"]) {
            id value = valueOrNil(modelDictionary, @"back_female");
            if (value != nil) {
                self->_backFemale = value;
            }
            self->_spritesDirtyProperties.JRMSpritesDirtyPropertyBackFemale = 1;
        }
        if ([key isEqualToString:@"front_default"]) {
            id value = valueOrNil(modelDictionary, @"front_default");
            if (value != nil) {
                self->_frontDefault = value;
            }
            self->_spritesDirtyProperties.JRMSpritesDirtyPropertyFrontDefault = 1;
        }
        if ([key isEqualToString:@"back_shiny"]) {
            id value = valueOrNil(modelDictionary, @"back_shiny");
            if (value != nil) {
                self->_backShiny = value;
            }
            self->_spritesDirtyProperties.JRMSpritesDirtyPropertyBackShiny = 1;
        }
        if ([key isEqualToString:@"back_shiny_female"]) {
            id value = valueOrNil(modelDictionary, @"back_shiny_female");
            if (value != nil) {
                self->_backShinyFemale = value;
            }
            self->_spritesDirtyProperties.JRMSpritesDirtyPropertyBackShinyFemale = 1;
        }
        if ([key isEqualToString:@"front_female"]) {
            id value = valueOrNil(modelDictionary, @"front_female");
            if (value != nil) {
                self->_frontFemale = value;
            }
            self->_spritesDirtyProperties.JRMSpritesDirtyPropertyFrontFemale = 1;
        }
        if ([key isEqualToString:@"back_default"]) {
            id value = valueOrNil(modelDictionary, @"back_default");
            if (value != nil) {
                self->_backDefault = value;
            }
            self->_spritesDirtyProperties.JRMSpritesDirtyPropertyBackDefault = 1;
        }
    }];
    if ([self class] == [JRMSprites class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(PlankModelInitTypeDefault) }];
    }
    return self;
}
- (instancetype)initWithBuilder:(JRMSpritesBuilder *)builder
{
    NSParameterAssert(builder);
    return [self initWithBuilder:builder initType:PlankModelInitTypeDefault];
}
- (instancetype)initWithBuilder:(JRMSpritesBuilder *)builder initType:(PlankModelInitType)initType
{
    NSParameterAssert(builder);
    if (!(self = [super init])) {
        return self;
    }
    _frontShinyFemale = builder.frontShinyFemale;
    _frontShiny = builder.frontShiny;
    _backFemale = builder.backFemale;
    _frontDefault = builder.frontDefault;
    _backShiny = builder.backShiny;
    _backShinyFemale = builder.backShinyFemale;
    _frontFemale = builder.frontFemale;
    _backDefault = builder.backDefault;
    _spritesDirtyProperties = builder.spritesDirtyProperties;
    if ([self class] == [JRMSprites class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(initType) }];
    }
    return self;
}
- (NSString *)debugDescription
{
    NSArray<NSString *> *parentDebugDescription = [[super debugDescription] componentsSeparatedByString:@"\n"];
    NSMutableArray *descriptionFields = [NSMutableArray arrayWithCapacity:8];
    [descriptionFields addObject:parentDebugDescription];
    struct JRMSpritesDirtyProperties props = _spritesDirtyProperties;
    if (props.JRMSpritesDirtyPropertyFrontShinyFemale) {
        [descriptionFields addObject:[@"_frontShinyFemale = " stringByAppendingFormat:@"%@", _frontShinyFemale]];
    }
    if (props.JRMSpritesDirtyPropertyFrontShiny) {
        [descriptionFields addObject:[@"_frontShiny = " stringByAppendingFormat:@"%@", _frontShiny]];
    }
    if (props.JRMSpritesDirtyPropertyBackFemale) {
        [descriptionFields addObject:[@"_backFemale = " stringByAppendingFormat:@"%@", _backFemale]];
    }
    if (props.JRMSpritesDirtyPropertyFrontDefault) {
        [descriptionFields addObject:[@"_frontDefault = " stringByAppendingFormat:@"%@", _frontDefault]];
    }
    if (props.JRMSpritesDirtyPropertyBackShiny) {
        [descriptionFields addObject:[@"_backShiny = " stringByAppendingFormat:@"%@", _backShiny]];
    }
    if (props.JRMSpritesDirtyPropertyBackShinyFemale) {
        [descriptionFields addObject:[@"_backShinyFemale = " stringByAppendingFormat:@"%@", _backShinyFemale]];
    }
    if (props.JRMSpritesDirtyPropertyFrontFemale) {
        [descriptionFields addObject:[@"_frontFemale = " stringByAppendingFormat:@"%@", _frontFemale]];
    }
    if (props.JRMSpritesDirtyPropertyBackDefault) {
        [descriptionFields addObject:[@"_backDefault = " stringByAppendingFormat:@"%@", _backDefault]];
    }
    return [NSString stringWithFormat:@"JRMSprites = {\n%@\n}", debugDescriptionForFields(descriptionFields)];
}
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(JRMSpritesBuilder *builder))block
{
    NSParameterAssert(block);
    JRMSpritesBuilder *builder = [[JRMSpritesBuilder alloc] initWithModel:self];
    block(builder);
    return [builder build];
}
- (BOOL)isEqual:(id)anObject
{
    if (self == anObject) {
        return YES;
    }
    if ([anObject isKindOfClass:[JRMSprites class]] == NO) {
        return NO;
    }
    return [self isEqualToSprites:anObject];
}
- (BOOL)isEqualToSprites:(JRMSprites *)anObject
{
    return (
        (anObject != nil) &&
        (self == anObject) &&
        (_frontShinyFemale == anObject.frontShinyFemale || [_frontShinyFemale isEqualToString:anObject.frontShinyFemale]) &&
        (_frontShiny == anObject.frontShiny || [_frontShiny isEqualToString:anObject.frontShiny]) &&
        (_backFemale == anObject.backFemale || [_backFemale isEqualToString:anObject.backFemale]) &&
        (_frontDefault == anObject.frontDefault || [_frontDefault isEqualToString:anObject.frontDefault]) &&
        (_backShiny == anObject.backShiny || [_backShiny isEqualToString:anObject.backShiny]) &&
        (_backShinyFemale == anObject.backShinyFemale || [_backShinyFemale isEqualToString:anObject.backShinyFemale]) &&
        (_frontFemale == anObject.frontFemale || [_frontFemale isEqualToString:anObject.frontFemale]) &&
        (_backDefault == anObject.backDefault || [_backDefault isEqualToString:anObject.backDefault])
    );
}
- (NSUInteger)hash
{
    NSUInteger subhashes[] = {
        17,
        [_frontShinyFemale hash],
        [_frontShiny hash],
        [_backFemale hash],
        [_frontDefault hash],
        [_backShiny hash],
        [_backShinyFemale hash],
        [_frontFemale hash],
        [_backDefault hash]
    };
    return PINIntegerArrayHash(subhashes, sizeof(subhashes) / sizeof(subhashes[0]));
}
- (instancetype)mergeWithModel:(JRMSprites *)modelObject
{
    return [self mergeWithModel:modelObject initType:PlankModelInitTypeFromMerge];
}
- (instancetype)mergeWithModel:(JRMSprites *)modelObject initType:(PlankModelInitType)initType
{
    NSParameterAssert(modelObject);
    JRMSpritesBuilder *builder = [[JRMSpritesBuilder alloc] initWithModel:self];
    [builder mergeWithModel:modelObject];
    return [[JRMSprites alloc] initWithBuilder:builder initType:initType];
}
#pragma mark - NSCopying
- (id)copyWithZone:(NSZone *)zone
{
    return self;
}
#pragma mark - NSSecureCoding
+ (BOOL)supportsSecureCoding
{
    return YES;
}
- (instancetype)initWithCoder:(NSCoder *)aDecoder
{
    if (!(self = [super init])) {
        return self;
    }
    _frontShinyFemale = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"front_shiny_female"];
    _frontShiny = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"front_shiny"];
    _backFemale = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"back_female"];
    _frontDefault = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"front_default"];
    _backShiny = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"back_shiny"];
    _backShinyFemale = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"back_shiny_female"];
    _frontFemale = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"front_female"];
    _backDefault = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"back_default"];
    _spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShinyFemale = [aDecoder decodeIntForKey:@"front_shiny_female_dirty_property"] & 0x1;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShiny = [aDecoder decodeIntForKey:@"front_shiny_dirty_property"] & 0x1;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyBackFemale = [aDecoder decodeIntForKey:@"back_female_dirty_property"] & 0x1;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyFrontDefault = [aDecoder decodeIntForKey:@"front_default_dirty_property"] & 0x1;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyBackShiny = [aDecoder decodeIntForKey:@"back_shiny_dirty_property"] & 0x1;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyBackShinyFemale = [aDecoder decodeIntForKey:@"back_shiny_female_dirty_property"] & 0x1;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyFrontFemale = [aDecoder decodeIntForKey:@"front_female_dirty_property"] & 0x1;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyBackDefault = [aDecoder decodeIntForKey:@"back_default_dirty_property"] & 0x1;
    if ([self class] == [JRMSprites class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(PlankModelInitTypeDefault) }];
    }
    return self;
}
- (void)encodeWithCoder:(NSCoder *)aCoder
{
    [aCoder encodeObject:self.frontShinyFemale forKey:@"front_shiny_female"];
    [aCoder encodeObject:self.frontShiny forKey:@"front_shiny"];
    [aCoder encodeObject:self.backFemale forKey:@"back_female"];
    [aCoder encodeObject:self.frontDefault forKey:@"front_default"];
    [aCoder encodeObject:self.backShiny forKey:@"back_shiny"];
    [aCoder encodeObject:self.backShinyFemale forKey:@"back_shiny_female"];
    [aCoder encodeObject:self.frontFemale forKey:@"front_female"];
    [aCoder encodeObject:self.backDefault forKey:@"back_default"];
    [aCoder encodeInt:_spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShinyFemale forKey:@"front_shiny_female_dirty_property"];
    [aCoder encodeInt:_spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShiny forKey:@"front_shiny_dirty_property"];
    [aCoder encodeInt:_spritesDirtyProperties.JRMSpritesDirtyPropertyBackFemale forKey:@"back_female_dirty_property"];
    [aCoder encodeInt:_spritesDirtyProperties.JRMSpritesDirtyPropertyFrontDefault forKey:@"front_default_dirty_property"];
    [aCoder encodeInt:_spritesDirtyProperties.JRMSpritesDirtyPropertyBackShiny forKey:@"back_shiny_dirty_property"];
    [aCoder encodeInt:_spritesDirtyProperties.JRMSpritesDirtyPropertyBackShinyFemale forKey:@"back_shiny_female_dirty_property"];
    [aCoder encodeInt:_spritesDirtyProperties.JRMSpritesDirtyPropertyFrontFemale forKey:@"front_female_dirty_property"];
    [aCoder encodeInt:_spritesDirtyProperties.JRMSpritesDirtyPropertyBackDefault forKey:@"back_default_dirty_property"];
}
@end

@implementation JRMSpritesBuilder
- (instancetype)initWithModel:(JRMSprites *)modelObject
{
    NSParameterAssert(modelObject);
    if (!(self = [super init])) {
        return self;
    }
    struct JRMSpritesDirtyProperties spritesDirtyProperties = modelObject.spritesDirtyProperties;
    if (spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShinyFemale) {
        _frontShinyFemale = modelObject.frontShinyFemale;
    }
    if (spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShiny) {
        _frontShiny = modelObject.frontShiny;
    }
    if (spritesDirtyProperties.JRMSpritesDirtyPropertyBackFemale) {
        _backFemale = modelObject.backFemale;
    }
    if (spritesDirtyProperties.JRMSpritesDirtyPropertyFrontDefault) {
        _frontDefault = modelObject.frontDefault;
    }
    if (spritesDirtyProperties.JRMSpritesDirtyPropertyBackShiny) {
        _backShiny = modelObject.backShiny;
    }
    if (spritesDirtyProperties.JRMSpritesDirtyPropertyBackShinyFemale) {
        _backShinyFemale = modelObject.backShinyFemale;
    }
    if (spritesDirtyProperties.JRMSpritesDirtyPropertyFrontFemale) {
        _frontFemale = modelObject.frontFemale;
    }
    if (spritesDirtyProperties.JRMSpritesDirtyPropertyBackDefault) {
        _backDefault = modelObject.backDefault;
    }
    _spritesDirtyProperties = spritesDirtyProperties;
    return self;
}
- (JRMSprites *)build
{
    return [[JRMSprites alloc] initWithBuilder:self];
}
- (void)mergeWithModel:(JRMSprites *)modelObject
{
    NSParameterAssert(modelObject);
    JRMSpritesBuilder *builder = self;
    if (modelObject.spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShinyFemale) {
        builder.frontShinyFemale = modelObject.frontShinyFemale;
    }
    if (modelObject.spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShiny) {
        builder.frontShiny = modelObject.frontShiny;
    }
    if (modelObject.spritesDirtyProperties.JRMSpritesDirtyPropertyBackFemale) {
        builder.backFemale = modelObject.backFemale;
    }
    if (modelObject.spritesDirtyProperties.JRMSpritesDirtyPropertyFrontDefault) {
        builder.frontDefault = modelObject.frontDefault;
    }
    if (modelObject.spritesDirtyProperties.JRMSpritesDirtyPropertyBackShiny) {
        builder.backShiny = modelObject.backShiny;
    }
    if (modelObject.spritesDirtyProperties.JRMSpritesDirtyPropertyBackShinyFemale) {
        builder.backShinyFemale = modelObject.backShinyFemale;
    }
    if (modelObject.spritesDirtyProperties.JRMSpritesDirtyPropertyFrontFemale) {
        builder.frontFemale = modelObject.frontFemale;
    }
    if (modelObject.spritesDirtyProperties.JRMSpritesDirtyPropertyBackDefault) {
        builder.backDefault = modelObject.backDefault;
    }
}
- (void)setFrontShinyFemale:(NSString *)frontShinyFemale
{
    _frontShinyFemale = frontShinyFemale;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShinyFemale = 1;
}
- (void)setFrontShiny:(NSString *)frontShiny
{
    _frontShiny = frontShiny;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyFrontShiny = 1;
}
- (void)setBackFemale:(NSString *)backFemale
{
    _backFemale = backFemale;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyBackFemale = 1;
}
- (void)setFrontDefault:(NSString *)frontDefault
{
    _frontDefault = frontDefault;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyFrontDefault = 1;
}
- (void)setBackShiny:(NSString *)backShiny
{
    _backShiny = backShiny;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyBackShiny = 1;
}
- (void)setBackShinyFemale:(NSString *)backShinyFemale
{
    _backShinyFemale = backShinyFemale;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyBackShinyFemale = 1;
}
- (void)setFrontFemale:(NSString *)frontFemale
{
    _frontFemale = frontFemale;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyFrontFemale = 1;
}
- (void)setBackDefault:(NSString *)backDefault
{
    _backDefault = backDefault;
    _spritesDirtyProperties.JRMSpritesDirtyPropertyBackDefault = 1;
}
@end
