//
//  JRMType.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class JRMTypeBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface JRMType : NSObject<NSCopying, NSSecureCoding>
@property (nullable, nonatomic, strong, readonly) NSDictionary * type;
@property (nonatomic, assign, readonly) NSInteger slot;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(JRMTypeBuilder *)builder;
- (instancetype)initWithBuilder:(JRMTypeBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(JRMTypeBuilder *builder))block;
- (BOOL)isEqualToType:(JRMType *)anObject;
- (instancetype)mergeWithModel:(JRMType *)modelObject;
- (instancetype)mergeWithModel:(JRMType *)modelObject initType:(PlankModelInitType)initType;
@end

@interface JRMTypeBuilder : NSObject
@property (nullable, nonatomic, strong, readwrite) NSDictionary * type;
@property (nonatomic, assign, readwrite) NSInteger slot;
- (instancetype)initWithModel:(JRMType *)modelObject;
- (JRMType *)build;
- (void)mergeWithModel:(JRMType *)modelObject;
@end

NS_ASSUME_NONNULL_END
